baseURL = "https://gcatalfamo.github.io/bulma-hugo-example/"
dataDir = "data/"
languageCode = "en-us"
staticDir = "static/"
summaryLength = 10
theme = "bulma-hugo-theme"
themesDir = "themes/"
title = "Bulma + Hugo sample website"
enableRobotsTXT = true
[[menu.nav]]
URL = "about"
name = "About Us"
weight = 1
[[menu.nav]]
URL = "guides"
name = "Guides"
weight = 2
[[menu.nav]]
URL = "news"
name = "News"
weight = 3
[[menu.nav]]
URL = "blog"
name = "Blog"
weight = 4
[[menu.nav]]
URL = "contact-us"
name = "Call to action"
url = "https://github.com/gcatalfamo/bulma-hugo-example"
weight = 5
[params]
author = "CUSTOM author"
description = "CUSTOM theme"
home = "Home"
logo = "images/logo.png"
csv = "static/Book1.csv"
[params.footer]
copyright = "Company copyright"
copyrightURL = "https://gcatalfamo.github.io/bulma-hugo-example/"
isSocial = false
[[params.footer.socialIcon]]
icon = "tf-ion-social-facebook"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-twitter"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-google-outline"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-youtube"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-linkedin"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-dribbble-outline"
url = "#"
[[params.footer.socialIcon]]
icon = "tf-ion-social-pinterest-outline"
url = "#"
[params.menu]
activeStyle = "has-text-weight-bold has-text-warning"
brandName = "YOUR BRAND HERE"
menuAccent = "Call to action"
navCtaIcon = "fab fa-github"
navStyle = "is-small is-dark"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
